import re

with open('public/index.html', 'r', encoding='utf-8') as f:
    content = f.read()

# Comprehensive i18n dictionary
expanded_i18n = """const i18n = {
      ar: {
        // Navigation & Brand
        brand_title: "فَسِيلَة",
        brand_subtitle: "المنصة التشاركية لزيتون سوريا",
        nav_home: "الرئيسية",
        nav_marketplace: "سوق الأشجار",
        nav_dashboard: "محفظتي",
        nav_farmer: "بوابة المزارع",
        nav_mill: "بوابة المعاصر",
        nav_chat: "تحدث مع فسيلة",
        nav_browse: "سوق الأشجار",

        // Hero
        hero_badge: "منظومة متكاملة: مزارع • معاصر حديثة • مستثمرون • توثيق زمني",
        hero_title_1: "استثمر في",
        hero_title_2: "شجرة زيتون",
        hero_title_3: "وشارك الأرض بركتها وثمارها",
        hero_title_full: "استثمر في <span class=\\"text-terracotta-500 underline decoration-olive-600 underline-offset-8\\">شجرة زيتون</span><br>وشارك الأرض بركتها وثمارها",
        hero_desc: "اشترِ حصة موثقة في شجرة زيتون عريقة في سوريا، تابع نموها ورعايتها، وراقب عصر ثمارها في أحدث المعاصر المعتمدة مع شهادات جودة مخبرية ونسب حموضة مضمونة، واستلم زيتك البكر أو عوائدك أينما كنت.",
        hero_btn_explore: "تصفح سوق الأشجار المتاحة",
        hero_btn_chat: "استشر \\"فسيلة\\" فوراً",
        hero_stat_1_lbl: "شجرة موثقة بنظام GPS",
        hero_stat_2_lbl: "نسبة حموضة الزيت (بكر ممتاز)",
        hero_stat_3_lbl: "عصر بارد بمعاصر معتمدة",
        hero_stat_4_lbl: "عائلة مزارعة شريكة",
        hero_feat_badge: "شجرة الموسم المميزة",
        hero_feat_region: "طرطوس • الدريكيش",
        hero_feat_name: "الشجرة المعمرة - حارسة الجبل",
        hero_feat_desc: "زيتون خضيري أصيل غرس عام 1948. معتمدة لدى معصرة الدريكيش الحديثة لإنتاج زيت فائق النقاء بحموضة 0.32%.",
        hero_feat_lab: "شهادة جودة مخبرية",
        hero_feat_avail: "متاح 50% من الحصص",
        per_share_unit: "/ الحصة",

        // Seasonal Calendar
        calendar_badge: "تقويم المواسم السورية",
        calendar_title: "دورة رعاية وإنتاج الزيتون على مدار العام",
        calendar_subtitle: "شاهد كيف تتكامل رعاية المزارع مع تقارير التوثيق وعمل المعاصر في كل فصل",
        cal_q1_month: "كانون الثاني – شباط",
        cal_q1_title: "التقليم الشتوي والتسميد",
        cal_q1_desc: "تقليم الأغصان الجافة وتهوية قلب الشجرة مع إضافة التسميد العضوي البلدي لحفظ خصوبة التربة.",
        cal_q1_badge: "تقرير وصور التقليم",
        cal_q2_month: "نيسان – أيار",
        cal_q2_title: "الإزهار والعقد الأولي",
        cal_q2_desc: "ظهور الأزهار البيضاء الكثيفة وتحولها إلى حبات زيتون صغيرة واعدة، مع مراقبة رطوبة الأرض.",
        cal_q2_badge: "تقرير نسبة عقد الثمار",
        cal_q3_month: "تموز – آب",
        cal_q3_title: "الري التكميلي والمكافحة",
        cal_q3_desc: "ري تكميلي بمياه الينابيع خلال موجات الحر لحماية الحبات من الجفاف مع وضع مصائد فرمونية حيوية.",
        cal_q3_badge: "تسجيل صوتي للمزارع",
        cal_q4_month: "تشرين الأول – تشرين الثاني",
        cal_q4_title: "موسم القطاف والعصر البارد",
        cal_q4_desc: "القطاف اليدوي ونقل الثمار فوراً إلى المعصرة الحديثة لإجراء العصر البارد وإصدار شهادات الجودة.",
        cal_q4_badge: "شهادة الفحص المخبري وتوزيع الزيت",

        // Interactive ROI Calculator
        calc_badge: "حاسبة الاستثمار والأثر التفاعلية",
        calc_title: "احسب عوائدك وأثرك البيئي المباشر في سوريا",
        calc_desc: "حرك المؤشر لاختيار عدد الحصص واكتشف كمية زيت الزيتون البكر المتوقعة ومقدار الكربون الممتص سنوياً",
        calc_shares_label: "حجم الاستثمار (عدد الحصص):",
        calc_scale_1: "1 حصة (25%)",
        calc_scale_4: "شجرة كاملة (4 حصص)",
        calc_scale_8: "شجرتان (8 حصص)",
        calc_include_title: "ماذا تشمل الحصة الواحدة؟",
        calc_include_desc: "رعاية زراعية سنوية متكاملة (سقاية، تقليم، مكافحة حيوية) + عصر على البارد في معصرة معتمدة + شهادة ملكية وجودة رقمية موثقة بالـ GPS.",
        calc_card1_title: "زيت زيتون بكر ممتاز",
        calc_card1_sub: "عصر بارد حموضة < 0.4%",
        calc_card2_title: "امتصاص ثاني أكسيد الكربون",
        calc_card2_sub: "أثر بيئي ومكافحة تصحر",
        calc_card3_title: "تكلفة الاستثمار الكلية",
        calc_card3_sub: "دفع محلي أو دولي",
        calc_card4_title: "العائد التقديري السنوي",
        calc_card4_sub: "قيمة الزيت أو المردود",
        calc_oil_lbl: "ناتج الزيت السنوي",
        calc_carbon_lbl: "امتصاص الكربون",
        calc_oil_unit: "لتر زيت صافي",

        // Call To Action
        cta_title: "انضم إلى مجتمع مستثمري ومزارعي فسيلة",
        cta_desc: "أكثر من 2,400 شجرة زيتون موثقة بالـ GPS ومعاصر حديثة جاهزة لاستقبال مواسم الخير.",
        cta_btn_market: "استكشف الأشجار المتاحة",
        cta_btn_mill: "بوابة أصحاب المعاصر",

        // Marketplace
        market_title: "سوق أشجار الزيتون السورية",
        market_subtitle: "تصفح الأشجار المتاحة مع تفاصيل المعاصر الشريكة وشهادات الجودة",
        market_available_label: "الأشجار المتاحة:",
        market_search_ph: "ابحث باسم الشجرة، المزرعة، المحافظة (طرطوس، إدلب، درعا)، أو صنف الزيتون...",
        filter_region_lbl: "المحافظة / المنطقة",
        filter_region_all: "جميع المحافظات",
        filter_region_tartus: "طرطوس (الساحل)",
        filter_region_idlib: "إدلب (جبل الزاوية)",
        filter_region_daraa: "درعا (سهل حوران)",
        filter_age_lbl: "عمر الشجرة",
        filter_age_all: "جميع الأعمار",
        filter_age_heritage: "معمرة (أكثر من 50 سنة)",
        filter_age_prime: "مثمرة بالغة (20 - 50 سنة)",
        filter_age_young: "حديثة الإثمار (أقل من 20 سنة)",
        filter_price_lbl: "سعر الحصة",
        filter_price_all: "كافة الأسعار",
        filter_price_low: "أقل من $25",
        filter_price_mid: "$25 - $30",
        filter_price_high: "أكثر من $30",
        filter_reset_btn: "إعادة ضبط الفلاتر",

        // Tree Details
        tree_detail_back: "العودة إلى سوق الأشجار",
        tree_stewardship_title: "الاستثمار التشاركي المعتمد",
        tree_planted_label: "العمر:",
        tree_variety_label: "الصنف:",
        tree_annual_yield_label: "الإنتاج التقديري:",
        tree_carbon_label: "امتصاص الكربون:",
        tree_avail_label: "المتاح:",
        tree_mill_quality_title: "المعصرة المعتمدة والفحص المخبري:",
        tree_timeline_title: "الخط الزمني للرعاية والرسائل الصوتية الميدانية",
        tree_by_farmer: "بواسطة المزارع: ",

        // Investor Dashboard
        dash_title: "محفظتي في فسيلة",
        dash_subtitle: "متابعة أداء أشجارك، الحصص المملوكة، والشهادات الرقمية المعتمدة",
        dash_btn_cert: "عرض شهادة الملكية الرقمية",
        dash_btn_order_oil: "طلب تسليم عبوات الزيت",
        dash_stat_invest: "إجمالي الاستثمار",
        dash_stat_invest_sub: "حصة موثقة في شجرة معمرة",
        dash_stat_oil: "إنتاج الزيت المتوقع",
        dash_stat_oil_sub: "موسم خريف 2026",
        dash_stat_carbon: "أثر امتصاص الكربون",
        dash_stat_carbon_sub: "مساهمة بيئية مستدامة",
        dash_stat_trees: "الأشجار المملوكة",
        dash_stat_trees_sub: "ريف طرطوس",
        dash_tab_trees: "أشجاري في فسيلة",
        dash_tab_txs: "سجل العمليات والمدفوعات",
        dash_tx_ref: "رقم المرجع",
        dash_tx_type: "نوع العملية",
        dash_tx_amount: "المبلغ",
        dash_tx_method: "وسيلة الدفع",
        dash_tx_status: "الحالة",
        dash_tx_date: "التاريخ",

        // Farmer Portal
        farmer_welcome_title: "أهلاً بك يا عم أبو أحمد الطرطوسي 🌿",
        farmer_welcome_sub: "مزرعة كروم الكردي العريقة • الدريكيش، طرطوس • لست بحاجة للكتابة، يمكنك توثيق كل أعمالك بصوتك مباشرة!",
        farmer_title: "بوابة المزارع الميداني • نظام صوتي ميسر",
        farmer_btn_record: "سجّل عملك بصوتك الآن",
        farmer_btn_voice_guide: "استمع للتوجيهات الصوتية (بدون قراءة)",
        farmer_btn_emergency: "نداء طوارئ زراعي",
        farmer_wallet_title: "محفظة مستحقات وأتعاب الرعاية الزراعية",
        farmer_wallet_sub: "بدلات العمل الميداني المعتمدة من مساهمات المستثمرين",
        farmer_btn_payout: "طلب سحب نقدي (سيريتل كاش / الهرم)",
        farmer_stat_total: "إجمالي مستحقات الرعاية",
        farmer_stat_paid: "أتعاب مدفوعة ومستلمة",
        farmer_stat_ready: "رصيد جاهز للصرف",
        farmer_trees_section: "أشجار الزيتون المكلف برعايتها",
        farmer_audio_feed_title: "أحدث التسجيلات الصوتية الميدانية",

        // Mill Portal
        mill_title: "بوابة أصحاب معاصر الزيتون الحديثة (Olive Mills)",
        mill_subtitle: "إدارة دفعات العصر، قياس نسب الحموضة، وإصدار شهادات الجودة المخبرية",
        mill_btn_new_batch: "تسجيل دفعة عصر وإصدار شهادة جودة",
        mill_stat_olives: "إجمالي ثمار الزيتون المستلمة",
        mill_stat_oil: "زيت بكر ممتاز منتج",
        mill_stat_acidity: "متوسط نسبة الحموضة",
        mill_stat_certs: "شهادات الفحص الصادرة",
        mill_th_serial: "رقم الدفعة / السيريال",
        mill_th_tree: "الشجرة والمزرعة",
        mill_th_weight: "وزن الثمار (كغ)",
        mill_th_oil: "الزيت الناتج (لتر)",
        mill_th_acidity: "نسبة الحموضة",
        mill_th_temp: "حرارة العصر",
        mill_th_grade: "درجة الجودة",
        mill_th_cert: "الشهادة المخبرية",

        // Faseela Assistant Chat
        chat_launcher_text: "تحدث مع فسيلة",
        chat_title: "فَسِيلَة",
        chat_badge: "دليلك الفلاحي",
        chat_status: "جاهزة للإجابة بدقة عن كافة التفاصيل",
        chat_input_ph: "اكتب سؤالك لفسيلة بكل وضوح...",
        chat_chip_pay: "💳 الدفع بسيريتل كاش",
        chat_chip_yield: "🫒 إنتاج الزيت والعوائد",
        chat_chip_cultivars: "🌿 الأصناف (صوراني/خضيري)",
        chat_chip_mill: "⚙️ فحص المعاصر والجودة",
        chat_chip_shipping: "📦 شحن الزيت للخارج",
        chat_chip_visit: "📍 زيارة الشجرة والـ GPS",
        chat_scroll_down: "النزول للرسائل الأحدث",

        // Common Buttons & Labels
        btn_details: "التفاصيل",
        btn_buy_share: "اشترِ حصة",
        btn_view_tree: "معاينة الشجرة",
        btn_view_cert: "معاينة وتحميل الشهادة",
        btn_close: "إغلاق",
        btn_cancel: "إلغاء",
        btn_confirm: "تأكيد الاستثمار",
        lab_cert_btn: "شهادة التحليل المخبري",
        listen_audio: "استماع",
        age_label: "عمر",
        year_unit: "عاماً",
        avail_label: "متاح",
        oil_yield_label: "لتر زيت/سنة",
        carbon_label: "كغ كربون/سنة",
        share_unit: "الحصة (25%)",

        // Footer
        footer_tagline: "منصة تشاركية لحماية وتنمية أشجار الزيتون السورية العريقة وربط المغتربين بأرض الوطن.",
        footer_regions_title: "المحافظات المشمولة بالتوثيق:",
        footer_regions_list: "طرطوس • إدلب • درعا • حلب (عفرين) • ريف دمشق",
        footer_support_title: "مركز الدعم والاستعلام:",
        footer_rights: "جميع الحقوق محفوظة لمنصة فسيلة © 2026 • حماية وتنمية الزيتون السوري"
      },
      en: {
        // Navigation & Brand
        brand_title: "FASEELA",
        brand_subtitle: "Syrian Olive Tree Fractional Stewardship",
        nav_home: "Home",
        nav_marketplace: "Tree Marketplace",
        nav_dashboard: "My Portfolio",
        nav_farmer: "Farmer Portal",
        nav_mill: "Mill Portal",
        nav_chat: "Talk with Faseela",
        nav_browse: "Marketplace",

        // Hero
        hero_badge: "Integrated Ecosystem: Farmers • Modern Mills • Global Investors • Field Audits",
        hero_title_1: "Invest in a",
        hero_title_2: "Syrian Olive Tree",
        hero_title_3: "& Share the Land's Heritage and Bounty",
        hero_title_full: "Invest in a <span class=\\"text-terracotta-500 underline decoration-olive-600 underline-offset-8\\">Syrian Olive Tree</span><br>& Share the Land's Heritage and Bounty",
        hero_desc: "Own a certified fractional share of an authentic heritage olive tree in Syria. Follow its seasonal care, monitor cold pressing at modern certified mills with lab certificates, and receive your extra virgin olive oil or financial returns anywhere in the world.",
        hero_btn_explore: "Explore Available Trees",
        hero_btn_chat: "Ask \\"Faseela\\" Now",
        hero_stat_1_lbl: "GPS Documented Trees",
        hero_stat_2_lbl: "Acidity (Extra Virgin)",
        hero_stat_3_lbl: "Cold Pressed & Lab Certified",
        hero_stat_4_lbl: "Partner Farming Families",
        hero_feat_badge: "Featured Season Tree",
        hero_feat_region: "Tartus • Dreikish",
        hero_feat_name: "The Century Olive - Mountain Guardian",
        hero_feat_desc: "Authentic Khodairi olive planted in 1948. Certified at Dreikish Modern Mill producing ultra-pure EVOO with 0.32% acidity.",
        hero_feat_lab: "Lab Quality Certified",
        hero_feat_avail: "50% Shares Available",
        per_share_unit: "/ Share",

        // Seasonal Calendar
        calendar_badge: "Syrian Seasons Calendar",
        calendar_title: "Year-Round Syrian Olive Care Cycle",
        calendar_subtitle: "See how field farming, digital evidence, and modern cold mills synchronize across four seasons",
        cal_q1_month: "January – February",
        cal_q1_title: "Winter Pruning & Organic Feeding",
        cal_q1_desc: "Thinning dry branches to aerate the canopy and adding compost to preserve natural soil fertility.",
        cal_q1_badge: "Pruning Photos & Log",
        cal_q2_month: "April – May",
        cal_q2_title: "Flowering & Fruit Setting",
        cal_q2_desc: "Dense white blossoms develop into promising olive fruitlets with soil moisture monitoring.",
        cal_q2_badge: "Fruit-Set Assessment",
        cal_q3_month: "July – August",
        cal_q3_title: "Supplemental Irrigation & Bio-Defense",
        cal_q3_desc: "Spring-fed irrigation during heatwaves to protect fruits alongside eco-friendly pheromone traps.",
        cal_q3_badge: "Farmer Audio Field Note",
        cal_q4_month: "October – November",
        cal_q4_title: "Hand Harvest & Cold Pressing",
        cal_q4_desc: "Careful hand picking and same-day transfer to modern mills for cold pressing under 25°C.",
        cal_q4_badge: "Lab Quality Cert & Oil Dispatch",

        // Interactive ROI Calculator
        calc_badge: "Interactive ROI & Impact Calculator",
        calc_title: "Calculate Your Real Returns & Syrian Impact",
        calc_desc: "Slide to adjust your share fraction and see estimated extra virgin oil, carbon offset, and economics",
        calc_shares_label: "Stewardship Size (Shares):",
        calc_scale_1: "1 Share (25%)",
        calc_scale_4: "Whole Tree (4 Shares)",
        calc_scale_8: "Two Trees (8 Shares)",
        calc_include_title: "What does a single share include?",
        calc_include_desc: "Comprehensive yearly orchard stewardship (irrigation, pruning, bio protection) + modern cold pressing + GPS-tagged digital ownership & lab purity certificates.",
        calc_card1_title: "Extra Virgin Olive Oil",
        calc_card1_sub: "Cold Pressed • Acidity < 0.4%",
        calc_card2_title: "Annual CO2 Absorption",
        calc_card2_sub: "Environmental Impact & Green Cover",
        calc_card3_title: "Total Stewardship Cost",
        calc_card3_sub: "Local or International Checkout",
        calc_card4_title: "Estimated Annual Oil Value",
        calc_card4_sub: "Market Value / Financial Return",
        calc_oil_lbl: "Est. Annual Oil",
        calc_carbon_lbl: "Carbon Offset",
        calc_oil_unit: "L Pure EVOO",

        // Call To Action
        cta_title: "Join the Faseela Stewardship Community",
        cta_desc: "Over 2,400 GPS-documented trees and certified modern mills ready for authentic stewardship.",
        cta_btn_market: "Explore Available Trees",
        cta_btn_mill: "Olive Mills Portal",

        // Marketplace
        market_title: "Syrian Olive Trees Marketplace",
        market_subtitle: "Browse verified trees with partner cold-press mills and lab purity reports",
        market_available_label: "Available Trees:",
        market_search_ph: "Search by tree name, farm, region (Tartus, Idlib, Daraa), or olive variety...",
        filter_region_lbl: "Province / Region",
        filter_region_all: "All Provinces",
        filter_region_tartus: "Tartus (Coastal)",
        filter_region_idlib: "Idlib (Zawiya Mountain)",
        filter_region_daraa: "Daraa (Hauran Plains)",
        filter_age_lbl: "Tree Age",
        filter_age_all: "All Ages",
        filter_age_heritage: "Heritage (50+ years)",
        filter_age_prime: "Prime Fruiting (20 - 50 yrs)",
        filter_age_young: "Young (under 20 yrs)",
        filter_price_lbl: "Share Price",
        filter_price_all: "All Prices",
        filter_price_low: "Under $25",
        filter_price_mid: "$25 - $30",
        filter_price_high: "Over $30",
        filter_reset_btn: "Reset Filters",

        // Tree Details
        tree_detail_back: "Back to Marketplace",
        tree_stewardship_title: "Certified Fractional Stewardship",
        tree_planted_label: "Planted Year:",
        tree_variety_label: "Variety:",
        tree_annual_yield_label: "Est. Annual Oil:",
        tree_carbon_label: "Carbon Offset:",
        tree_avail_label: "Available:",
        tree_mill_quality_title: "Certified Mill & Laboratory Quality:",
        tree_timeline_title: "Field Care Timeline & Farmer Voice Notes",
        tree_by_farmer: "By Farmer: ",

        // Investor Dashboard
        dash_title: "My Faseela Portfolio",
        dash_subtitle: "Track your trees, fractional shares, and verified digital certificates",
        dash_btn_cert: "View Digital Certificate",
        dash_btn_order_oil: "Order Olive Oil Delivery",
        dash_stat_invest: "Total Invested",
        dash_stat_invest_sub: "Verified Tree Share",
        dash_stat_oil: "Expected Oil Yield",
        dash_stat_oil_sub: "Autumn 2026 Season",
        dash_stat_carbon: "Carbon Offset Impact",
        dash_stat_carbon_sub: "Sustainable Green Contribution",
        dash_stat_trees: "Trees Owned",
        dash_stat_trees_sub: "Tartus Countryside",
        dash_tab_trees: "My Trees in Faseela",
        dash_tab_txs: "Transactions & Receipts Log",
        dash_tx_ref: "Reference #",
        dash_tx_type: "Transaction Type",
        dash_tx_amount: "Amount",
        dash_tx_method: "Payment Method",
        dash_tx_status: "Status",
        dash_tx_date: "Date",

        // Farmer Portal
        farmer_welcome_title: "Welcome, Partner Farmer Abu Ahmad 🌿",
        farmer_welcome_sub: "Al-Kurdi Heritage Farm • Dreikish, Tartus • No typing needed, record and document all your work by voice!",
        farmer_title: "Field Farmer Portal • Voice-First Accessibility",
        farmer_btn_record: "Record Care by Voice",
        farmer_btn_voice_guide: "Listen to Voice Guidance",
        farmer_btn_emergency: "Emergency Field Alert",
        farmer_wallet_title: "Farmer Care & Labor Wallet",
        farmer_wallet_sub: "Approved field allowances funded by investor stewardship shares",
        farmer_btn_payout: "Request Cash Payout (Syriatel / Al-Haram)",
        farmer_stat_total: "Total Care Earnings",
        farmer_stat_paid: "Paid & Withdrawn",
        farmer_stat_ready: "Balance Ready for Payout",
        farmer_trees_section: "Assigned Olive Trees Under Care",
        farmer_audio_feed_title: "Latest Field Voice Reports",

        // Mill Portal
        mill_title: "Modern Olive Mills Portal",
        mill_subtitle: "Manage pressing batches, record acidity measurements, and issue digital lab certificates",
        mill_btn_new_batch: "Record Pressing Batch & Issue Lab Cert",
        mill_stat_olives: "Total Olives Received",
        mill_stat_oil: "Extra Virgin Oil Produced",
        mill_stat_acidity: "Average Oil Acidity",
        mill_stat_certs: "Lab Certificates Issued",
        mill_th_serial: "Batch Serial #",
        mill_th_tree: "Tree & Farm",
        mill_th_weight: "Fruit Weight (kg)",
        mill_th_oil: "Oil Yield (L)",
        mill_th_acidity: "Acidity %",
        mill_th_temp: "Press Temp",
        mill_th_grade: "Quality Grade",
        mill_th_cert: "Lab Certificate",

        // Faseela Assistant Chat
        chat_launcher_text: "Talk with Faseela",
        chat_title: "FASEELA",
        chat_badge: "Agricultural Advisor",
        chat_status: "Ready to answer all your questions",
        chat_input_ph: "Ask Faseela anything about olive investments...",
        chat_chip_pay: "💳 Syriatel Cash & Banks",
        chat_chip_yield: "🫒 Oil Yields & Returns",
        chat_chip_cultivars: "🌿 Varieties (Sourani/Khodairi)",
        chat_chip_mill: "⚙️ Cold Mills & Acidity",
        chat_chip_shipping: "📦 Overseas Shipping",
        chat_chip_visit: "📍 GPS & Grove Visits",
        chat_scroll_down: "Scroll to latest",

        // Common Buttons & Labels
        btn_details: "Details",
        btn_buy_share: "Buy Share",
        btn_view_tree: "View Tree",
        btn_view_cert: "View & Download Certificate",
        btn_close: "Close",
        btn_cancel: "Cancel",
        btn_confirm: "Confirm Investment",
        lab_cert_btn: "Lab Quality Certificate",
        listen_audio: "Listen",
        age_label: "Age",
        year_unit: "yrs",
        avail_label: "Avail",
        oil_yield_label: "L Oil / yr",
        carbon_label: "kg CO2 / yr",
        share_unit: "Share (25%)",

        // Footer
        footer_tagline: "Fractional platform preserving heritage Syrian olive trees and connecting global stewards to their ancestral soil.",
        footer_regions_title: "Provinces Covered by GPS Registry:",
        footer_regions_list: "Tartus • Idlib • Daraa • Aleppo (Afrin) • Rural Damascus",
        footer_support_title: "Support & Inquiries:",
        footer_rights: "All rights reserved to Faseela Platform © 2026 • Syrian Olive Stewardship"
      }
    };"""

print("Expanded i18n prepared.")
